### ISSUE TITLE
채팅방 만들기

### ISSUE THREAD

**Issue by ChoMk** [Basicbug/Messenger_Android#9]
- UI구성
- usecase 정리
- 구현...

**Comment by bsgreentea** [comment]
@ChoMk 
딱히 뭐 한건 없지만.. 채팅방 구성한거 맞게 했는지 한번 봐주세요...ㅎ

**Comment by bsgreentea** [comment]
- 메세지 리스트를 위에서 아래로 당겼을 때, 로컬 메세지가 중복 로드되지 않도록 구현하기

**Comment by bsgreentea** [comment]
쿼리 수정하기


메세지 리스트 상단에 로드되도록 수정하기


delay시에 중복 안되는것 확인 완료
